spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: gatcha
      auto-index-creation: true

server:
  port: 8080

jwt:
  secret: gatchaSecretKey123456789012345678901234567890
  expiration: 3600000 # 1 hour
